### ISSUE TITLE
Not working for upgrade jquery 1 to 3

### ISSUE THREAD

**Issue by vpberiya** [yireo-training/magento2-example-jquery-upgrade#1]
I have integrated all files into my theme folder.

then after I checked in the browser getting some error in the console and also check the jquery version from the console than getting the old version of the jquery

Screenshot URL
[https://prnt.sc/10cnxef](https://prnt.sc/10cnxef
)
Magento Version 2.2.5

**Comment by jissereitsma** [comment]
Note that this is a prototype and it requires you to be a developer to be proactive in troubleshooting things. Using a Magento version that made zero effort for being jQuery 3 compatible doesn't help. First step: Upgrade to a Magento version that is supported and that made steps towards jQuery. Suggestion: Upgrade to the latest Magento version before trying to fix anything else.

**Comment by vpberiya** [comment]
@jissereitsma 
Can you please suggest which Magento version supported by Jquery?

**Comment by vpberiya** [comment]
Okay Thank You

**Comment by jissereitsma** [comment]
You are missing the point: Use the latest Magento version, period. Why are you persisting on using 2.2.5 while it is outdated and insecure? Upgrading to the latest version is a common thing. Which latest version? Simply "the latest version". I can't help you with finding the version number of that.
